import React from "react";
import {
  ArrowLeft,
  UserCheck,
  Star,
  Award,
  Zap,
  TrendingUp,
  Clock,
} from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Cell,
} from "recharts";
import Badge from "../../components/ui/Badge";
import { STAFF_PERFORMANCE_DATA } from "../../data/reports";

/**
 * Custom Staff Chart Tooltip
 */
const CustomStaffTooltip = ({ active, payload }) => {
  if (active && payload && payload.length) {
    const data = payload[0]?.payload;
    return (
      <div className="bg-bg-sidebar text-text-white text-xs p-3 rounded-xl shadow-xl border border-border/20">
        <p className="font-bold text-base text-primary-light">{data.name}</p>
        <p className="text-[11px] text-text-muted">{data.role}</p>
        <p className="font-extrabold text-emerald-400 text-sm mt-1.5">
          Revenue: Rs. {data.sales?.toLocaleString()}
        </p>
        <p className="text-text-muted text-[11px] mt-0.5">
          {data.orders} Orders • {data.speed}
        </p>
      </div>
    );
  }
  return null;
};

/**
 * Smart POS - Staff Performance Report Component
 */
export default function StaffReport({ onBack }) {
  const topPerformer = STAFF_PERFORMANCE_DATA[1]; // Sara Bibi with 152k

  return (
    <div className="space-y-4 sm:space-y-6">
      
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-bg-card rounded-2xl p-3.5 sm:p-4 border border-border shadow-xs">
        <div className="flex items-center gap-3">
          {onBack && (
            <button
              type="button"
              onClick={onBack}
              className="p-2 rounded-xl hover:bg-bg-hover text-text-secondary hover:text-text-primary transition-colors cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
            </button>
          )}
          <div>
            <h2 className="text-lg sm:text-xl font-bold text-text-primary">
              Staff Sales & Service Speed Report
            </h2>
            <p className="text-xs text-text-muted">
              Analyze order taker efficiency, waiter revenues, and guest satisfaction ratings
            </p>
          </div>
        </div>

        <Badge variant="purple">4 Active Floor Staff</Badge>
      </div>

      {/* Top Performer Ribbon Card */}
      <div className="p-4 sm:p-5 rounded-2xl bg-purple-50/80 border border-purple-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 rounded-2xl bg-purple-700 text-white flex items-center justify-center font-bold text-lg shadow-sm shrink-0">
            <Award className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-purple-700 bg-purple-100 px-2 py-0.5 rounded-md">
              👑 Top Server of the Week
            </span>
            <h3 className="text-base font-bold text-purple-950 mt-1">
              {topPerformer.name} ({topPerformer.role})
            </h3>
            <p className="text-xs text-purple-800">
              Generated <span className="font-bold">Rs. {topPerformer.sales.toLocaleString()}</span> with 5.0 Star Guest Rating
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto text-xs font-bold text-purple-900 bg-white px-3.5 py-2 rounded-xl border border-purple-200 shadow-2xs">
          <Zap className="w-4 h-4 text-purple-600" />
          <span>{topPerformer.speed} fulfillment speed</span>
        </div>
      </div>

      {/* STAFF REVENUE BAR CHART */}
      <div className="bg-bg-card rounded-2xl p-4 sm:p-5 border border-border shadow-xs space-y-3">
        <div className="flex items-center justify-between border-b border-border-light pb-3">
          <div>
            <h3 className="font-bold text-sm sm:text-base text-text-primary flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-primary" />
              <span>Revenue Generated by Staff Member</span>
            </h3>
            <p className="text-xs text-text-muted">Total sales value billed per staff account</p>
          </div>
        </div>

        <div className="w-full h-64 pt-2">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={STAFF_PERFORMANCE_DATA} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" horizontal={false} />
              <XAxis
                type="number"
                tick={{ fontSize: 11, fill: "#64748b" }}
                axisLine={false}
                tickLine={false}
                tickFormatter={(val) => `Rs.${val / 1000}k`}
              />
              <YAxis
                dataKey="name"
                type="category"
                tick={{ fontSize: 11, fill: "#0f172a", fontWeight: 600 }}
                axisLine={false}
                tickLine={false}
                width={95}
              />
              <Tooltip content={<CustomStaffTooltip />} />
              <Bar dataKey="sales" name="Sales (PKR)" fill="#2563eb" radius={[0, 6, 6, 0]}>
                {STAFF_PERFORMANCE_DATA.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={entry.name === topPerformer.name ? "#8b5cf6" : "#2563eb"}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Staff Table */}
      <div className="bg-bg-card rounded-2xl border border-border overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs min-w-[650px]">
            <thead className="bg-bg-main border-b border-border text-text-muted uppercase text-[10px] font-bold">
              <tr>
                <th className="px-5 py-3.5">Staff Member</th>
                <th className="px-5 py-3.5">Role</th>
                <th className="px-5 py-3.5 text-center">Orders Served</th>
                <th className="px-5 py-3.5 text-center">Service Speed</th>
                <th className="px-5 py-3.5 text-right">Revenue Generated</th>
                <th className="px-5 py-3.5 text-center">Rating</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-light text-text-primary">
              {STAFF_PERFORMANCE_DATA.map((s, idx) => (
                <tr key={idx} className="hover:bg-bg-hover">
                  <td className="px-5 py-4 font-bold text-text-primary flex items-center gap-2">
                    <div className="w-7 h-7 rounded-lg bg-bg-main border border-border flex items-center justify-center font-bold text-xs text-primary">
                      {s.name[0]}
                    </div>
                    <span>{s.name}</span>
                  </td>
                  <td className="px-5 py-4 text-text-secondary">{s.role}</td>
                  <td className="px-5 py-4 text-center font-bold text-primary">
                    {s.orders} orders
                  </td>
                  <td className="px-5 py-4 text-center text-text-muted font-medium">
                    {s.speed}
                  </td>
                  <td className="px-5 py-4 text-right font-extrabold text-emerald-600">
                    Rs. {s.sales.toLocaleString()}
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className="inline-flex items-center gap-1 font-bold text-amber-600 bg-amber-50 px-2.5 py-0.5 rounded-full border border-amber-200">
                      <Star className="w-3 h-3 fill-amber-500 text-amber-500" />
                      <span>{s.rating}</span>
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
